<?php
// @codingStandardsIgnoreFile

/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php if ($block->canShowBlock()): ?>
    <?php // Absolunet Custom Code (luma template + filter wrapper)?>
    <div id="off-canvas-filters" class="filter-wrapper off-canvas position-left in-canvas-for-large" data-off-canvas data-position="left" data-transition="overlap">
        <button class="close-button" aria-label="<?= __('Close') ?>" type="button" data-close>
            <span aria-hidden="true"><?= __('Close') ?></span>
        </button>
        <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
            <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
            <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */ $filtered ?>">
                <span data-role="title"><?= /* @escapeNotVerified */ __('Filters') ?></span>
            </div>
            <?= $block->getChildHtml('state') ?>
            <div class="block-content filter-content">
                <?php $wrapOptions = false; ?>
                <?php foreach ($block->getFilters() as $filter): ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <?php if (!$wrapOptions): ?>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                        <?php  $wrapOptions = true; endif; ?>
                        <div data-role="collapsible" class="filter-options-item">
                            <div data-role="title" class="filter-options-title"><?= /* @escapeNotVerified */ __($filter->getName()) ?></div>
                            <div data-role="content" class="filter-options-content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?></div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
                    </div>
                <?php else: ?>
                    <script>
                        require([
                            'jquery'
                        ], function ($) {
                            $('#layered-filter-block').addClass('filter-no-options');
                        });
                    </script>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?php // /Absolunet Custom Code ?>
<?php endif; ?>
