<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$label = __("My account");
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
    $label = $block->escapeHtml($block->getLabel());
}
?>

<?php if (!$block->isLoggedIn() || $block->getIsSub()): ?>

<li class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes(); ?><?= /* @noEscape */ $dataPostParam; ?>>
        <?= $label; ?>
    </a>
</li>

<?php endif; ?>
