<?php
/**
 *
 * @author      Maude Payette <mpayette@absolunet.com>
 * @copyright   Copyright (c) 2017 Absolunet (http://www.absolunet.com)
 * @link        http://www.absolunet.com
 */

// @codingStandardsIgnoreFile

/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if($block->customerLoggedIn()): ?>
    <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <button type="button"
                    class="action switch"
                    tabindex="-1"
                    data-action="customer-menu-toggle">
                <?= $block->escapeHtml(__('My account')) ?>
            </button>
        </span>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
        <?php if($block->getChildHtml()):?>
            <div class="customer-menu" data-target="dropdown">
                <?= $block->getChildHtml();?>
            </div>
        <?php endif; ?>
    </li>
<?php endif; ?>
